/*
 * Verb family for every CONNECTOR_CATALOG slug. Featured is mixed, so this
 * map is by slug, not UI category. modeRule() prints the family sentence.
 * A missing catalog slug fails import (and therefore build/test).
 */
import { CONNECTOR_CATALOG, resolveConnector } from "@/lib/connectors";

export const CONNECTOR_FAMILIES = [
  "mail",
  "git",
  "docs",
  "calendar",
  "chat",
  "money",
  "search",
  "hosting",
] as const;

export type ConnectorFamily = (typeof CONNECTOR_FAMILIES)[number];

const FAMILY_SLUGS: Record<ConnectorFamily, readonly string[]> = {
  mail: [
    "agentmail",
    "bento-chat",
    "gmail",
    "outlook",
    "resend",
  ],
  git: [
    "buildkite",
    "claude-code",
    "coderabbit",
    "codex",
    "codex-cli",
    "compound-engineering",
    "create-plugin",
    "cursor-background-agents",
    "cursor-cloud-agents",
    "cursor-team-kit",
    "github",
    "github-actions",
    "gitlab",
    "harness",
    "pr-review-canvas",
    "sourcegraph",
    "superpowers",
    "tabnine",
    "tabnine-context-engine",
  ],
  docs: [
    "airtable",
    "aituber",
    "anki",
    "asana",
    "ashby",
    "atlassian",
    "atlassian-forge",
    "atlassian-teamwork-graph",
    "bible",
    "blender",
    "box",
    "canva",
    "castos",
    "chatprd",
    "circleback",
    "clickup",
    "cloudinary",
    "docs-canvas",
    "docusign",
    "dropbox",
    "excalidraw",
    "exiftool",
    "figma",
    "gamma",
    "gitbook",
    "godot",
    "google-docs",
    "google-drive",
    "google-sheets",
    "google-slides",
    "granola",
    "gsap",
    "here-now",
    "heygen",
    "higgsfield",
    "hirenimbus",
    "hyperframes",
    "icepanel",
    "icloud",
    "kindle",
    "kobbe",
    "linear",
    "lucid",
    "magic-patterns",
    "magicpath",
    "mainframe",
    "manufact",
    "maxfusion",
    "microsoft-dataverse",
    "mintlify",
    "miro",
    "monday-com",
    "notion",
    "onedrive",
    "orchestrate",
    "paper",
    "photos",
    "postman",
    "remotion",
    "sanity",
    "shadcn-ui",
    "sharepoint",
    "shopify",
    "soundcheck",
    "squarespace",
    "subtext",
    "svelte",
    "thermos",
    "tldraw",
    "unity",
    "videngineer",
    "webflow",
    "wix",
    "zapier",
  ],
  calendar: [
    "calendly",
    "google-calendar",
    "luma",
    "outlook-calendar",
    "zoom",
  ],
  chat: [
    "adlicio",
    "affonso",
    "amplemarket",
    "apollo-io",
    "apple-search-ads",
    "bulkpublish",
    "clay",
    "converly",
    "delulu-social",
    "discord",
    "feedhive",
    "ferndesk",
    "google-ads",
    "grok-bot",
    "help-scout",
    "helpspot",
    "hotmention",
    "hubspot",
    "instagram",
    "intercom",
    "linkedin",
    "microsoft-teams",
    "omnisocials",
    "onesignal",
    "outreach",
    "plain",
    "post-bridge",
    "postiz",
    "postnitro",
    "profound",
    "quiverai",
    "reddit",
    "refgrow",
    "salesforce",
    "sinch",
    "slack",
    "threads",
    "tiktok",
    "twilio",
    "x",
    "x-ads",
    "youtube",
    "zendesk",
  ],
  money: [
    "1inch",
    "adanos-market-sentiment",
    "airwallex",
    "airwallex-agentos",
    "airwallex-developer",
    "chargebee",
    "circle",
    "d-amp-b-risk-analytics",
    "etoro",
    "hyperliquid",
    "interactive-brokers",
    "kraken",
    "navan",
    "nuvio",
    "phantom",
    "plaid",
    "quickbooks",
    "raisely",
    "ramp",
    "revenuecat",
    "revenuecat-play-billing",
    "revolut-x",
    "s-and-p-global",
    "stripe",
    "stripe-link",
    "webull",
    "whop",
    "xero",
  ],
  search: [
    "1password",
    "agent-compatibility",
    "ahrefs",
    "aikido",
    "aleph",
    "amazon",
    "amd",
    "amplitude",
    "apify",
    "arize",
    "arxiv",
    "astronomer",
    "atlan",
    "atscale",
    "auth0",
    "aviation-weather-center",
    "axiom",
    "bee",
    "bing",
    "bot-directory",
    "braintrust",
    "bright-data",
    "browser-use",
    "browserbase",
    "browserstack",
    "chainguard",
    "checkmarx",
    "cisco-thousandeyes",
    "clerk",
    "clickflow",
    "clickhouse",
    "cockroachdb",
    "comp-ai",
    "composio",
    "confidence-by-spotify",
    "context-dev",
    "context7",
    "continual-learning",
    "coralogix",
    "corridor",
    "costco",
    "crowdstrike",
    "d-amp-b-commercial-graph",
    "dagster",
    "databricks",
    "datadog",
    "dataforseo",
    "datarobot",
    "dbt-labs",
    "dynatrace",
    "elastic",
    "endor-labs-agent-kit",
    "exa",
    "faa-notam-search",
    "falconer",
    "firecrawl",
    "firetiger",
    "githits",
    "glean",
    "gong",
    "google-analytics",
    "google-cloud-bigquery",
    "google-flights",
    "google-maps",
    "google-search",
    "grafana-cloud",
    "grafana-labs",
    "hacker-news",
    "hex",
    "hugging-face",
    "indexnow",
    "infisical",
    "juicebox",
    "langfuse",
    "meltwater",
    "mem0",
    "merge",
    "meta-reality-labs",
    "meticulous",
    "mixpanel",
    "mobbin",
    "modern-web-guidance",
    "mongodb",
    "mongodb-atlas",
    "monk-io",
    "neon-postgres",
    "nvidia-skills",
    "observe-by-snowflake",
    "omni",
    "opensearch",
    "pagerduty",
    "paradedb",
    "parallel",
    "pendo",
    "pinecone",
    "planetscale",
    "playwright",
    "posthog",
    "react-doctor",
    "redis",
    "resolve-ai",
    "revyl",
    "roboflow",
    "sales-navigator",
    "scandit",
    "screenshotone",
    "scylladb",
    "search-console",
    "semgrep",
    "semrush",
    "sentry",
    "skillselion",
    "snowflake",
    "snyk",
    "snyk-api-amp-web",
    "sonarqube",
    "sonatype",
    "stacktree",
    "stayingapi",
    "tavily",
    "thoughtspot",
    "tierzero",
    "transcriptapi",
    "trends-vc",
    "turbopuffer",
    "web-search",
    "whole-foods",
    "whole-foods-delivery",
    "workos",
    "yandex",
    "zenity",
    "zillapi",
    "zoominfo",
    "zscaler",
  ],
  hosting: [
    "adobe-developer-app-builder",
    "amazon-location-service",
    "antimetal",
    "appwrite",
    "aws-agents",
    "aws-amplify",
    "aws-core",
    "aws-data-analytics",
    "aws-databases",
    "aws-deployments",
    "aws-sagemaker",
    "aws-serverless",
    "azure",
    "azure-cosmos-db",
    "cloudflare",
    "convex",
    "encore",
    "firebase",
    "forge",
    "hostinger",
    "jfrog",
    "launchdarkly",
    "lovable",
    "netlify",
    "opsera",
    "port",
    "prisma",
    "railway",
    "render",
    "runlayer",
    "supabase",
    "temporal",
    "vantage",
    "vercel",
  ],
};

const FAMILY_BY_SLUG = new Map<string, ConnectorFamily>();
for (const family of CONNECTOR_FAMILIES) {
  for (const slug of FAMILY_SLUGS[family]) FAMILY_BY_SLUG.set(slug, family);
}

const MISSING_FAMILIES = CONNECTOR_CATALOG.filter((entry) => !FAMILY_BY_SLUG.has(entry.slug)).map((entry) => entry.slug);
if (MISSING_FAMILIES.length > 0) {
  throw new Error(`CONNECTOR_CATALOG slug has no verb family: ${MISSING_FAMILIES.join(", ")}`);
}

export function connectorFamily(connector: string): ConnectorFamily {
  const slug = resolveConnector(connector).slug;
  const family = FAMILY_BY_SLUG.get(slug);
  if (!family) {
    throw new Error(`CONNECTOR_CATALOG slug "${slug}" has no verb family`);
  }
  return family;
}

export function catalogFamilyCoverage(): { slug: string; family: ConnectorFamily }[] {
  return CONNECTOR_CATALOG.map((entry) => {
    const family = FAMILY_BY_SLUG.get(entry.slug);
    if (!family) throw new Error(`CONNECTOR_CATALOG slug "${entry.slug}" has no verb family`);
    return { slug: entry.slug, family };
  });
}
