export const ledger = {
  paper: "var(--page)",
  paperDeep: "var(--surface)",
  ink: "var(--ink)",
  inkSoft: "var(--ink-soft)",
  inkFaint: "var(--muted)",
  inkMuted: "var(--ink-soft)",
  label: "var(--muted)",
  numeral: "var(--muted)",
  oxblood: "var(--accent)",
  accentText: "var(--accent-text)",
  green: "var(--status-live)",
  hairline: "var(--line)",
  leader: "var(--leader)",
  serif: "var(--font-outfit), system-ui, sans-serif",
  display: "var(--font-outfit), system-ui, sans-serif",
  mono: 'ui-monospace, "SF Mono", "SFMono-Regular", Menlo, "Cascadia Code", monospace',
} as const;

export const ledgerOg = {
  paper: "#ffffff",
  paperDeep: "#f5f4f2",
  ink: "#0a0a0a",
  inkSoft: "#3d3d3d",
  inkFaint: "#8a8a8a",
  inkMuted: "#3d3d3d",
  label: "#8a8a8a",
  numeral: "#8a8a8a",
  oxblood: "#0891b2",
  green: "#1f7a46",
  hairline: "#eceae6",
  leader: "#d9d6d0",
} as const;
